name: ghstack
author: Shikanime Deva
branding:
  icon: globe
  color: gray-dark
description: Land a pull request
inputs:
  app-id:
    description: The GitHub App ID
    required: true
  private-key:
    description: The GitHub App private key
    required: true
  base:
    description: The base branch to rebase onto
    default: main
  reaction:
    description: The reaction to add
    default: rocket
  permissions:
    description: The permissions to check
    default: write,maintain,admin
  username:
    description: The username to use
    default: github-actions[bot]
  email:
    description: The email to use
    default: github-actions[bot]@users.noreply.github.com
  sign-commits:
    description: Set to true if the action should sign the commit with GPG
    default: "false"
  gpg-private-key:
    description: GPG Private Key with which to sign the commits in the PR to be created
    default: ""
  gpg-passphrase:
    description: GPG Private Key Passphrase for the GPG Private Key with which to sign the commits in the PR to be created
    default: ""
runs:
  using: composite
  steps:
    - id: createGithubAppToken
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: ./.github/actions/setup-sapling
    - uses: ./.github/actions/import-gpg
      with:
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: ${{ inputs.gpg-passphrase }}
      if: ${{ inputs.sign-commits == 'true' }}
    - uses: ./.github/actions/ghstack-land
      with:
        command: .land
        reaction: ${{ inputs.reaction }}
        permissions: ${{ inputs.permissions }}
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: ./.github/actions/ghstack-rebase
      with:
        base: ${{ inputs.base }}
        command: .rebase
        reaction: ${{ inputs.reaction }}
        permissions: ${{ inputs.permissions }}
        token: ${{ steps.createGithubAppToken.outputs.token }}
    - uses: ./.github/actions/ghstack-close
      with:
        command: .close
        reaction: ${{ inputs.reaction }}
        permissions: ${{ inputs.permissions }}
        token: ${{ steps.createGithubAppToken.outputs.token }}
