name: ghstack land
author: Shikanime Deva
branding:
  icon: globe
  color: gray-dark
description: Land a pull request
inputs:
  command:
    description: The command to run
    default: .land
  reaction:
    description: The reaction to add
    default: rocket
  permissions:
    description: The permissions to check
    default: write,maintain,admin
  token:
    description: The GitHub token
    required: true
runs:
  using: composite
  steps:
    - uses: github/command@v1
      id: command
      with:
        command: ${{ inputs.command }}
        reaction: ${{ inputs.reaction }}
        allowed_contexts: pull_request
        permissions: ${{ inputs.permissions }}
        github_token: ${{ inputs.token }}
    - shell: bash
      run: |
        sapling -- ghstack land \
          ${{ github.event.issue.pull_request.html_url }}
      if: ${{ steps.command.outputs.continue == 'true' }}
      env:
        GH_TOKEN: ${{ inputs.token }}
